spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/pipiservice?characterEncoding=utf8&serverTimezone=Asia/Shanghai
  #    username: root
  #    password: 3.14ylh0618
  datasource:
    url: jdbc:mysql://localhost:3306/advancedweb?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MYSQL5Dialect
jwt:
  token:
     secret: advancedweb2021
     validity: 18000000